### ISSUE TITLE
Add Background Image to Header of Content Page

### ISSUE THREAD

**Issue by c3spinoza** [c3spinoza/pollution_website#13]
To add an image to the header as a background add: 
`body {
  background-image: url('image.jpg');
  background-repeat: no-repeat;
  background-attachment: fixed;
  background-size: cover;
}`

For more info, go to: https://www.w3schools.com/html/html_images_background.asp

**Comment by Kyliehilsen** [comment]
Which location?

**Comment by c3spinoza** [comment]
@Kyliehilsen Well, VU as that is where the basis is. I was thinking that the background image in the header should be in all the content pages.

**Comment by c3spinoza** [comment]
I still think this is necessary.
