### ISSUE TITLE
Add Transitions to Other Pages 

### ISSUE THREAD

**Issue by c3spinoza** [c3spinoza/pollution_website#15]
We need to add a way to redirect people into a new page when they click one of that pages.

**Comment by c3spinoza** [comment]
Look at the slack group to find more info on this or you can look it up.

**Comment by c3spinoza** [comment]
@Rchen7, you are in charge of this. Make a pull request of the map branch.

**Comment by Rchen7** [comment]
@c3spinoza I made a pull request of the main branch consisting of the changes that I made (i added some generic links that would allow us to direct the users to each of our locations). Please check over it and let me know if everything looks good. Sorry this took so long, I must have missed this task.

**Comment by c3spinoza** [comment]
@Rchen7  They are good, but the thing is that they are not for the map. Look in the map branch and you will see that the main,html file is different.

**Comment by c3spinoza** [comment]
This pretty much done I think so I will close it.
