### ISSUE TITLE
Fix Content Pages

### ISSUE THREAD

**Issue by c3spinoza** [c3spinoza/pollution_website#19]
The content pages seems to be a little broken, so we need to fix that. Additionally, we need to add comments to make it easier to understand what each part does.

**Comment by Kyliehilsen** [comment]
I just added labels because i did it the wrong way last time

**Comment by c3spinoza** [comment]
Alright thank you.

**Comment by c3spinoza** [comment]
I made a new branch called content_page_V2 to sort for start from scratch, as I think it would be easier than messing around with fixing the original code.

**Comment by c3spinoza** [comment]
done
