### ISSUE TITLE
Create page for each location

### ISSUE THREAD

**Issue by c3spinoza** [c3spinoza/pollution_website#4]
We need to create the basis of a page from each location that we do. Base it off the sketch made.

**Comment by c3spinoza** [comment]
@Kyliehilsen or @eadet, can you all work on this? You just need to make one page not all. Also, try to use the basis from the main branch so you don't start from scratch.

**Comment by eadet** [comment]
So start coding the pages for our locations using the template from the main branch?

Also, about the AT&T building, I still haven't been able to find data on it, but I was able to find data on the Bridgestone/Firestone facility Dr. Haag mentioned, so I was wondering if it would be better to do that location instead?
